<a href="https://colab.research.google.com/github/silvia-jesus/CAR_Labrea/blob/main/CAR_RL_Labrea_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **CAR_RL_Labrea_02.ipynb**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

import glob
import os

!pip install geopandas
import geopandas as gpd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: geopandas in /usr/local/lib/python3.9/dist-packages (0.12.2)
Requirement already satisfied: pyproj>=2.6.1.post1 in /usr/local/lib/python3.9/dist-packages (from geopandas) (3.4.1)
Requirement already satisfied: shapely>=1.7 in /usr/local/lib/python3.9/dist-packages (from geopandas) (2.0.1)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from geopandas) (1.3.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from geopandas) (23.0)
Requirement already satisfied: fiona>=1.8 in /usr/local/lib/python3.9/dist-packages (from geopandas) (1.9.1)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (8.1.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (2022.12.7)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (0.7.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (22.2.0)
Requirement already satisfied: munch>=2.3.2 in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.0->geopandas) (1.22.4)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.0->geopandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.0->geopandas) (2.8.2)
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from munch>=2.3.2->fiona>=1.8->geopandas) (1.15.0)

/usr/local/lib/python3.9/dist-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
<ipython-input-2-09349ff75f03>:8: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd

In [ ]:
!sudo apt install libspatialindex-dev
!pip install rtree
!pip install pygeos

import rtree
import pygeos
gpd.options.use_pygeos = True
USE_PYGEOS=1

Reading package lists... Done
Building dependency tree
Reading state information... Done
libspatialindex-dev is already the newest version (1.9.3-1build1).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: rtree in /usr/local/lib/python3.9/dist-packages (1.0.1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pygeos in /usr/local/lib/python3.9/dist-packages (0.14)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.9/dist-packages (from pygeos) (1.22.4)

/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py:3249: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  if (await self.run_code(code, result,  async_=asy)):

In [ ]:
from pathlib import Path

In [ ]:
import time

In [ ]:
files_path_csv_RL = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_CSV/*csv'
files_list_csv_RL = glob.glob(files_path_csv_RL)

print(len(files_list_csv_RL))
files_list_csv_RL

1

['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_CSV/RL_1302405.csv']

In [ ]:
rl_append = pd.DataFrame()
#append all files together
for file in files_list_csv_RL:
            df_temp = pd.read_csv(file)
            rl_append = rl_append.append(df_temp, ignore_index=True)
rl_append.head()

,Unnamed: 0,IDF,NOM_TEMA,NUM_AREA,geometry,cd_mun
0,0,4293,Reserva Legal Proposta,26.447983,MULTIPOLYGON (((-66.84864918680367 -9.73083346...,1302405
1,1,5794,Reserva Legal Proposta,64.663560,POLYGON ((-66.86441218109029 -9.77281454847252...,1302405
2,2,8775,Reserva Legal Proposta,3860.282302,MULTIPOLYGON (((-66.60977200256998 -9.63313827...,1302405
3,3,8838,Reserva Legal Proposta,3340.201914,POLYGON ((-66.69523304157916 -9.60050989891182...,1302405
4,4,11600,Reserva Legal Proposta,2790.451345,MULTIPOLYGON (((-66.70014206321784 -9.68148839...,1302405

In [ ]:
rl_sumary = rl_append.groupby(['cd_mun','IDF'])['NUM_AREA'].sum().to_frame().reset_index()
rl_sumary

       cd_mun      IDF     NUM_AREA
0     1302405     4293    26.447983
1     1302405     5794    64.663560
2     1302405     8775  3860.282302
3     1302405     8838  3340.201914
4     1302405    11600  2790.451345
...       ...      ...          ...
2878  1302405  9940078    15.323261
2879  1302405  9940276    39.713417
2880  1302405  9940655    50.977706
2881  1302405  9944214    34.953100
2882  1302405  9944595    42.927513

[2883 rows x 3 columns]

In [ ]:
files_path_csv_IM = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IM_CSV/*csv'
files_list_csv_IM = glob.glob(files_path_csv_IM)

print(len(files_list_csv_IM))
files_list_csv_IM

1

['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IM_CSV/IMOVEL_IM_1302405_102033.shp.csv']

In [ ]:
im_append = pd.DataFrame()
#append all files together
for file in files_list_csv_IM:
            df_temp = pd.read_csv(file)
            im_append = im_append.append(df_temp, ignore_index=True)
im_append.head()

,Unnamed: 0,COD_IMOVEL,NUM_AREA,COD_ESTADO,NOM_MUNICI,NUM_MODULO,TIPO_IMOVE,SITUACAO,CONDICAO_I,geometry,cd_mun
0,0,AM-1302405-6F63EBF5EA864058B2B02CE6CE7C978F,59.316629,AM,Lábrea,0.5932,IRU,PE,"Analisado com pendências, aguardando retificaç...",POLYGON ((-734906.4028699504 2562229.824626518...,IM_1302405_102033.shp
1,1,AM-1302405-AA1907779A0F41A9A6B2223027F7A829,100.224892,AM,Lábrea,1.0022,IRU,PE,"Analisado com pendências, aguardando retificaç...",POLYGON ((-736595.7427354964 2557908.955268784...,IM_1302405_102033.shp
2,2,AM-1302405-D7B80B40290D4971BE914DC9A193EAD5,4924.316935,AM,Lábrea,51.3135,IRU,AT,"Analisado com pendências, aguardando retificaç...",POLYGON ((-710176.7652978672 2573995.712642175...,IM_1302405_102033.shp
3,3,AM-1302405-450B753B24744318B6EA3DDC40A32C5D,4175.209638,AM,Lábrea,41.7521,IRU,PE,"Analisado com pendências, aguardando retificaç...",POLYGON ((-720061.6789893549 2577243.662826002...,IM_1302405_102033.shp
4,4,AM-1302405-6AA5D37ECEC74951A4167DFA842906A3,538.786629,AM,Lábrea,5.3879,IRU,AT,Aguardando análise,POLYGON ((-724607.2482582927 2561645.336290520...,IM_1302405_102033.shp

In [ ]:
print(im_append.shape)
print(rl_append.shape)

(3527, 11)
(2890, 6)

In [ ]:
im_append['COD_IMOVEL'].nunique()

3527

In [ ]:
rl_append['IDF'].nunique()

2883

In [ ]:
im = im_append.groupby(['cd_mun'])['NUM_AREA'].sum().to_frame().reset_index()
im.head(10)

                  cd_mun      NUM_AREA
0  IM_1302405_102033.shp  6.626273e+06

Verificando se há cadastros que abrangem mais de um município

In [ ]:
im_mun = im_append.groupby('COD_IMOVEL')['cd_mun'].count().to_frame().sort_values(by=['cd_mun'],ascending=False)
im_mun

                                             cd_mun
COD_IMOVEL
AM-1300706-8A617E90BB084F0D8844E3709C44215B       1
AM-1302405-A8FB376973CC4B7EA688496F6FB5AD06       1
AM-1302405-A82663DC888A4AC8AC02426CE9EA159E       1
AM-1302405-A845E6BC408240C0A4971071B614ED16       1
AM-1302405-A84EE45C3E624900945EC62C5935F942       1
...                                             ...
AM-1302405-56C4C71FF6724461A118CDCF1344850D       1
AM-1302405-56CCA147407449139F7FF3A180D49F75       1
AM-1302405-56EFD9895E694E67843DF9E92838F9FE       1
AM-1302405-570B5A38A41E4BA2BCE80479531E211F       1
AM-1302405-FFD1264BA7B6495D998F19053170DAD5       1

[3527 rows x 1 columns]

**Junção espacial dos arquivos de Área do Imóvel**

In [ ]:
im_shp_path = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/AREA_IMOVEL_UNZIPPED/*shp'
im_shp_list = glob.glob(im_shp_path)

im_shp_list

['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/AREA_IMOVEL_UNZIPPED/IM_1302405_102033.shp']

In [ ]:
start = time.time()
im_geo = gpd.GeoDataFrame()
#append all files together
for file in im_shp_list:
            df_temp = gpd.read_file(file)
            im_geo = gpd.pd.concat([df_temp,im_geo])
print(im_geo.shape)
im_geo.head()

end = time.time()
duration = end-start

print(f'O processamento demorou {duration} segundos.')

(3527, 9)
O processamento demorou 1.9758021831512451 segundos.

In [ ]:
im_geo.head()

,COD_IMOVEL,NUM_AREA,COD_ESTADO,NOM_MUNICI,NUM_MODULO,TIPO_IMOVE,SITUACAO,CONDICAO_I,geometry
0,AM-1302405-6F63EBF5EA864058B2B02CE6CE7C978F,59.316629,AM,LÃ¡brea,0.5932,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...","POLYGON ((-734906.403 2562229.825, -734869.871..."
1,AM-1302405-AA1907779A0F41A9A6B2223027F7A829,100.224892,AM,LÃ¡brea,1.0022,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...","POLYGON ((-736595.743 2557908.955, -736330.354..."
2,AM-1302405-D7B80B40290D4971BE914DC9A193EAD5,4924.316935,AM,LÃ¡brea,51.3135,IRU,AT,"Analisado com pendÃªncias, aguardando retifica...","POLYGON ((-710176.765 2573995.713, -709583.330..."
3,AM-1302405-450B753B24744318B6EA3DDC40A32C5D,4175.209638,AM,LÃ¡brea,41.7521,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...","POLYGON ((-720061.679 2577243.663, -710778.119..."
4,AM-1302405-6AA5D37ECEC74951A4167DFA842906A3,538.786629,AM,LÃ¡brea,5.3879,IRU,AT,Aguardando anÃ¡lise,"POLYGON ((-724607.248 2561645.336, -724373.290..."

In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IM_JOIN'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IM_JOIN')

Path('./').mkdir(parents=True, exist_ok=True)

im_geo.to_file('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IM_JOIN/Imoveis_municipios.shp')

In [ ]:
im_geo.head()

,COD_IMOVEL,NUM_AREA,COD_ESTADO,NOM_MUNICI,NUM_MODULO,TIPO_IMOVE,SITUACAO,CONDICAO_I,geometry
0,AM-1302405-6F63EBF5EA864058B2B02CE6CE7C978F,59.316629,AM,LÃ¡brea,0.5932,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...","POLYGON ((-734906.403 2562229.825, -734869.871..."
1,AM-1302405-AA1907779A0F41A9A6B2223027F7A829,100.224892,AM,LÃ¡brea,1.0022,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...","POLYGON ((-736595.743 2557908.955, -736330.354..."
2,AM-1302405-D7B80B40290D4971BE914DC9A193EAD5,4924.316935,AM,LÃ¡brea,51.3135,IRU,AT,"Analisado com pendÃªncias, aguardando retifica...","POLYGON ((-710176.765 2573995.713, -709583.330..."
3,AM-1302405-450B753B24744318B6EA3DDC40A32C5D,4175.209638,AM,LÃ¡brea,41.7521,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...","POLYGON ((-720061.679 2577243.663, -710778.119..."
4,AM-1302405-6AA5D37ECEC74951A4167DFA842906A3,538.786629,AM,LÃ¡brea,5.3879,IRU,AT,Aguardando anÃ¡lise,"POLYGON ((-724607.248 2561645.336, -724373.290..."

**Junção espacial dos arquivos de Reserva Legal**

In [ ]:
rl_shp_path = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RESERVA_LEGAL_UNZIPPED/*shp'
rl_shp_list = glob.glob(rl_shp_path)

rl_shp_list

['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RESERVA_LEGAL_UNZIPPED/RL_1302405_102033.shp']

In [ ]:
start = time.time()
rl_geo = gpd.GeoDataFrame()
#append all files together
for file in rl_shp_list:
            df_temp = gpd.read_file(file)
            rl_geo = gpd.pd.concat([df_temp,rl_geo])
print(rl_geo.shape)
rl_geo.head()

end = time.time()
duration = end-start

print(f'O processamento demorou {duration} segundos.')

(2890, 4)
O processamento demorou 9.370046615600586 segundos.

In [ ]:
rl_geo.head()

,IDF,NOM_TEMA,NUM_AREA,geometry
0,4293,Reserva Legal Proposta,26.447983,"MULTIPOLYGON (((-735326.258 2561828.938, -7354..."
1,5794,Reserva Legal Proposta,64.663560,"POLYGON ((-736802.519 2557012.915, -737441.968..."
2,8775,Reserva Legal Proposta,3860.282302,"MULTIPOLYGON (((-710176.765 2573995.713, -7101..."
3,8838,Reserva Legal Proposta,3340.201914,"POLYGON ((-719515.961 2577273.955, -710782.569..."
4,11600,Reserva Legal Proposta,2790.451345,"MULTIPOLYGON (((-719638.511 2568112.346, -7141..."

In [ ]:
rl_geo.crs

<Derived Projected CRS: PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_Unk ...>
Name: unknown
Axis Info [cartesian]:
- [east]: Easting (metre)
- [north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unnamed
- method: Albers Equal Area
Datum: D_Unknown_based_on_Australian_Natl_S_Amer_1969_ellipsoid
- Ellipsoid: Australian_Natl_S_Amer_1969
- Prime Meridian: Greenwich

In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_JOIN'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_JOIN')

from pathlib import Path
Path('./').mkdir(parents=True, exist_ok=True)

rl_geo.to_file('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_JOIN/RL__municipios.shp')

Não há elemento de identificação entre Reserva Legal e Área do Imóvel, apenas a informação espacial (sobreposição das camadas). Sendo assim, será gerado o centroide dos polígonos de RL e então a identificação com os polígonos dos imóveis.

O processamento identificado acima não funcionou visto que há sobreposição de imóveis.

In [ ]:
start = time.time()

points_RL = rl_geo.copy()
points_RL['geometry'] = points_RL['geometry'].representative_point() #gera o centroide no interior do poligono
points_RL.head()

end = time.time()
duration = end-start

print(f'O processamento demorou {duration} segundos.')
print(points_RL.shape)

O processamento demorou 0.16488265991210938 segundos.
(2890, 4)

In [ ]:
start = time.time()

pts_RL_id = gpd.overlay(points_RL, im_geo, how='identity')


end = time.time()
duration = end-start
print(f'O processamento demorou {duration} segundos.')
print(pts_RL_id.shape)

pts_RL_id.head()

O processamento demorou 5.900587797164917 segundos.
(4665, 12)

,IDF,NOM_TEMA,NUM_AREA_1,COD_IMOVEL,NUM_AREA_2,COD_ESTADO,NOM_MUNICI,NUM_MODULO,TIPO_IMOVE,SITUACAO,CONDICAO_I,geometry
0,4293.0,Reserva Legal Proposta,26.447983,AM-1302405-6F63EBF5EA864058B2B02CE6CE7C978F,59.316629,AM,LÃ¡brea,0.5932,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...",POINT (-735017.150 2561958.450)
1,4293.0,Reserva Legal Proposta,26.447983,AM-1302405-109BD4CF010D47DF823CE75C009C3509,8445.161487,AM,LÃ¡brea,1.1895,AST,SU,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",POINT (-735017.150 2561958.450)
2,5794.0,Reserva Legal Proposta,64.663560,AM-1302405-109BD4CF010D47DF823CE75C009C3509,8445.161487,AM,LÃ¡brea,1.1895,AST,SU,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",POINT (-737440.354 2556805.283)
3,17235.0,Reserva Legal Proposta,4.899809,AM-1302405-109BD4CF010D47DF823CE75C009C3509,8445.161487,AM,LÃ¡brea,1.1895,AST,SU,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",POINT (-732268.328 2554301.540)
4,23637.0,Reserva Legal Proposta,1.793236,AM-1302405-109BD4CF010D47DF823CE75C009C3509,8445.161487,AM,LÃ¡brea,1.1895,AST,SU,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",POINT (-731145.788 2555256.222)

In [ ]:
pts_RL_id_sort = pts_RL_id.sort_values(by=['IDF'])
pts_RL_id_sort.head(10)

,IDF,NOM_TEMA,NUM_AREA_1,COD_IMOVEL,NUM_AREA_2,COD_ESTADO,NOM_MUNICI,NUM_MODULO,TIPO_IMOVE,SITUACAO,CONDICAO_I,geometry
0,4293.0,Reserva Legal Proposta,26.447983,AM-1302405-6F63EBF5EA864058B2B02CE6CE7C978F,59.316629,AM,LÃ¡brea,0.5932,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...",POINT (-735017.150 2561958.450)
1,4293.0,Reserva Legal Proposta,26.447983,AM-1302405-109BD4CF010D47DF823CE75C009C3509,8445.161487,AM,LÃ¡brea,1.1895,AST,SU,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",POINT (-735017.150 2561958.450)
2,5794.0,Reserva Legal Proposta,64.663560,AM-1302405-109BD4CF010D47DF823CE75C009C3509,8445.161487,AM,LÃ¡brea,1.1895,AST,SU,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",POINT (-737440.354 2556805.283)
44,5794.0,Reserva Legal Proposta,64.663560,AM-1302405-AA1907779A0F41A9A6B2223027F7A829,100.224892,AM,LÃ¡brea,1.0022,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...",POINT (-737440.354 2556805.283)
45,8775.0,Reserva Legal Proposta,3860.282302,AM-1302405-D7B80B40290D4971BE914DC9A193EAD5,4924.316935,AM,LÃ¡brea,51.3135,IRU,AT,"Analisado com pendÃªncias, aguardando retifica...",POINT (-717603.349 2571286.268)
48,8838.0,Reserva Legal Proposta,3340.201914,AM-1302405-7B668B7CA8B140F0A6A6887EEF02DC9F,4171.716050,AM,LÃ¡brea,41.7172,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...",POINT (-717168.751 2575032.295)
46,8838.0,Reserva Legal Proposta,3340.201914,AM-1302405-450B753B24744318B6EA3DDC40A32C5D,4175.209638,AM,LÃ¡brea,41.7521,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...",POINT (-717168.751 2575032.295)
52,11600.0,Reserva Legal Proposta,2790.451345,AM-1302405-0DD4D3FCFAA84F148122E96EF1DE5E0B,3573.523814,AM,LÃ¡brea,41.9990,IRU,AT,Em anÃ¡lise,POINT (-726259.926 2559178.527)
50,11600.0,Reserva Legal Proposta,2790.451345,AM-1302405-CED4FCFD20DF46C890816C442EF085E5,3576.352625,AM,LÃ¡brea,42.0323,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...",POINT (-726259.926 2559178.527)
58,11616.0,Reserva Legal Proposta,2371.328440,AM-1302405-22602DC7CE50494EB93E62CD9409CD17,2955.549085,AM,LÃ¡brea,29.5555,IRU,PE,"Analisado com pendÃªncias, aguardando retifica...",POINT (-731147.486 2565916.741)

In [ ]:
idf_im = pts_RL_id.groupby('IDF')['COD_IMOVEL'].count().to_frame().sort_values(by=['COD_IMOVEL'],ascending=False).reset_index()
idf_im

            IDF  COD_IMOVEL
0     4456833.0           8
1     6936258.0           6
2     9705288.0           6
3     4603995.0           6
4     4607914.0           6
...         ...         ...
2878  3263911.0           1
2879  4403630.0           1
2880  4403628.0           1
2881  4401226.0           1
2882  4023678.0           1

[2883 rows x 2 columns]

In [ ]:
idf_subset = pts_RL_id[pts_RL_id['IDF'] ==7603197]

idf_subset.head()

Empty GeoDataFrame
Columns: [IDF, NOM_TEMA, NUM_AREA_1, COD_IMOVEL, NUM_AREA_2, COD_ESTADO, NOM_MUNICI, NUM_MODULO, TIPO_IMOVE, SITUACAO, CONDICAO_I, geometry]
Index: []

In [ ]:
im_geo_diss = im_geo.dissolve('COD_IMOVEL')
print(im_geo.shape)
print(im_geo_diss.shape)

(3527, 9)
(3527, 8)

In [ ]:
rl_geo.head()

,IDF,NOM_TEMA,NUM_AREA,geometry
0,4293,Reserva Legal Proposta,26.447983,"MULTIPOLYGON (((-735326.258 2561828.938, -7354..."
1,5794,Reserva Legal Proposta,64.663560,"POLYGON ((-736802.519 2557012.915, -737441.968..."
2,8775,Reserva Legal Proposta,3860.282302,"MULTIPOLYGON (((-710176.765 2573995.713, -7101..."
3,8838,Reserva Legal Proposta,3340.201914,"POLYGON ((-719515.961 2577273.955, -710782.569..."
4,11600,Reserva Legal Proposta,2790.451345,"MULTIPOLYGON (((-719638.511 2568112.346, -7141..."

Shapely defines a Polygon as invalid if any of its segments intersect, including segments that are colinear.

In [ ]:
valid_rl = rl_geo[rl_geo.geometry.is_valid]
print(rl_geo.shape)
print(valid_rl.shape)

(2890, 4)
(2865, 4)

In [ ]:
valid_im = im_geo[im_geo.geometry.is_valid]
print(im_geo.shape)
print(valid_im.shape)

(3527, 9)
(3526, 9)

In [ ]:
rl_geo_diss = valid_rl.dissolve('IDF')
print(rl_geo_diss.shape)

(2860, 3)

In [ ]:
im_geo_diss = valid_im.dissolve('COD_IMOVEL')
print(im_geo_diss.shape)

(3526, 8)

In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_SPLIT/'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_SPLIT/')

Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
start = time.time()
n=rl_geo_diss.shape[0] #save each polygon in a different file in its respective category directory
for i in range(n):
    selection = rl_geo_diss.iloc[[i]]
    selection.reset_index(drop=False, inplace=True)
    name=selection.iloc[0]['IDF']

    selection.to_file(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_SPLIT/RL_{name}.shp')


end = time.time()
duration = end-start
print(f'O processamento demorou {duration} segundos.')

O processamento demorou 1637.199628829956 segundos.

In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IMOVEL_SPLIT'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IMOVEL_SPLIT')

Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
im_geo_diss.head()

,geometry,NUM_AREA,COD_ESTADO,NOM_MUNICI,NUM_MODULO,TIPO_IMOVE,SITUACAO,CONDICAO_I
COD_IMOVEL,,,,,,,,
AM-1300706-8A617E90BB084F0D8844E3709C44215B,"POLYGON ((-765238.245 2653072.230, -765518.003...",98.196978,AM,LÃ¡brea,0.9820,IRU,AT,"Analisado com pendÃªncias, aguardando retifica..."
AM-1300706-F14AB734CB734BBBAE3C0C4022E68E89,"POLYGON ((-711958.269 2684086.991, -711340.070...",88.945959,AM,LÃ¡brea,0.8895,IRU,PE,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£..."
AM-1302405-0004567FC620408DB04D3B5D0D065C77,"POLYGON ((-586222.719 2631210.018, -586348.006...",241.566756,AM,LÃ¡brea,2.4157,IRU,AT,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£..."
AM-1302405-00093CEED72A429FA3A8A08E4F51DC69,"POLYGON ((-713242.665 2674869.002, -714142.812...",101.479823,AM,LÃ¡brea,1.0148,IRU,AT,Em anÃ¡lise
AM-1302405-0015970D5F4F4FC392A2322104C9C3E6,"POLYGON ((-588682.279 2629085.633, -586378.993...",99.693348,AM,LÃ¡brea,0.9969,IRU,AT,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£..."

In [ ]:
im_geo_diss.dtypes

geometry      geometry
NUM_AREA       float64
COD_ESTADO      object
NOM_MUNICI      object
NUM_MODULO     float64
TIPO_IMOVE      object
SITUACAO        object
CONDICAO_I      object
dtype: object

In [ ]:
condicao = [(im_geo_diss.NUM_MODULO	>4),(im_geo_diss.NUM_MODULO	<=4) & (im_geo_diss.NUM_MODULO	>2),(im_geo_diss.NUM_MODULO	<=2) & (im_geo_diss.NUM_MODULO	>1),(im_geo_diss.NUM_MODULO	<=1)]
classes = ['IV','III','II','I']

im_geo_diss['Classe_MF'] = np.select(condicao, classes)

im_geo_diss.head()

,geometry,NUM_AREA,COD_ESTADO,NOM_MUNICI,NUM_MODULO,TIPO_IMOVE,SITUACAO,CONDICAO_I,Classe_MF
COD_IMOVEL,,,,,,,,,
AM-1300706-8A617E90BB084F0D8844E3709C44215B,"POLYGON ((-765238.245 2653072.230, -765518.003...",98.196978,AM,LÃ¡brea,0.9820,IRU,AT,"Analisado com pendÃªncias, aguardando retifica...",IV
AM-1300706-F14AB734CB734BBBAE3C0C4022E68E89,"POLYGON ((-711958.269 2684086.991, -711340.070...",88.945959,AM,LÃ¡brea,0.8895,IRU,PE,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",IV
AM-1302405-0004567FC620408DB04D3B5D0D065C77,"POLYGON ((-586222.719 2631210.018, -586348.006...",241.566756,AM,LÃ¡brea,2.4157,IRU,AT,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",II
AM-1302405-00093CEED72A429FA3A8A08E4F51DC69,"POLYGON ((-713242.665 2674869.002, -714142.812...",101.479823,AM,LÃ¡brea,1.0148,IRU,AT,Em anÃ¡lise,III
AM-1302405-0015970D5F4F4FC392A2322104C9C3E6,"POLYGON ((-588682.279 2629085.633, -586378.993...",99.693348,AM,LÃ¡brea,0.9969,IRU,AT,"Aguardando anÃ¡lise, nÃ£o passÃ­vel de revisÃ£...",IV

In [ ]:
start = time.time()
n=im_geo_diss.shape[0] #save each polygon in a different file in its respective category directory
for i in range(n):
    selection = im_geo_diss.iloc[[i]]
    selection.reset_index(drop=False, inplace=True)
    municipio=selection.iloc[0]['NOM_MUNICI']
    name=selection.iloc[0]['COD_IMOVEL']
    mf=selection.iloc[0]['Classe_MF']
    if not os.path.exists(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IMOVEL_SPLIT/{mf}'): #separa em pastas diferentes para não carregar a memória do Google Drive
      os.makedirs(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IMOVEL_SPLIT/{mf}')
    Path('./').mkdir(parents=True, exist_ok=True)

    selection.to_file(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IMOVEL_SPLIT/{mf}/IM_{municipio}_{name}.shp')


end = time.time()
duration = end-start
print(f'O processamento demorou {duration} segundos.')

O processamento demorou 385.5625157356262 segundos.

In [ ]:
im_geo_diss.groupby('Classe_MF')['geometry'].count()

Classe_MF
I       720
II      300
III     789
IV     1717
Name: geometry, dtype: int64